//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lokalizacija.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class langres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langres() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lokalizacija.Languages.langres", typeof(langres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InventoryCompanionⓇ - Aplikacija za popis.
        /// </summary>
        public static string AplikacijaZaPopisOtvorenihKolicina {
            get {
                return ResourceManager.GetString("AplikacijaZaPopisOtvorenihKolicina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brisanje.
        /// </summary>
        public static string Brisanje {
            get {
                return ResourceManager.GetString("Brisanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj kartice.
        /// </summary>
        public static string BrojKartice {
            get {
                return ResourceManager.GetString("BrojKartice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum i vreme skeniranja.
        /// </summary>
        public static string DatumIVremeSkeniranja {
            get {
                return ResourceManager.GetString("DatumIVremeSkeniranja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje skeniranja.
        /// </summary>
        public static string DodavanjeSkeniranja {
            get {
                return ResourceManager.GetString("DodavanjeSkeniranja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška!.
        /// </summary>
        public static string Greska_ {
            get {
                return ResourceManager.GetString("Greska!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID kartica.
        /// </summary>
        public static string IDKartica {
            get {
                return ResourceManager.GetString("IDKartica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID materijal.
        /// </summary>
        public static string IDMaterijal {
            get {
                return ResourceManager.GetString("IDMaterijal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID skeniranje.
        /// </summary>
        public static string IDSkeniranje {
            get {
                return ResourceManager.GetString("IDSkeniranje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime i prezime.
        /// </summary>
        public static string ImeIPrezime {
            get {
                return ResourceManager.GetString("ImeIPrezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izveštaj.
        /// </summary>
        public static string Izvestaj {
            get {
                return ResourceManager.GetString("Izvestaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izveštaj o skeniranim količinama.
        /// </summary>
        public static string IzvestajOSkeniranimKolicinama {
            get {
                return ResourceManager.GetString("IzvestajOSkeniranimKolicinama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvoz u Excel.
        /// </summary>
        public static string IzvozUExcel {
            get {
                return ResourceManager.GetString("IzvozUExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina.
        /// </summary>
        public static string Kolicina {
            get {
                return ResourceManager.GetString("Kolicina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentar.
        /// </summary>
        public static string Komentar {
            get {
                return ResourceManager.GetString("Komentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentar (opciono).
        /// </summary>
        public static string KomentarOpciono {
            get {
                return ResourceManager.GetString("KomentarOpciono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materijal pod tom oznakom ne postoji..
        /// </summary>
        public static string MaterijalPodTomOznakomNePostoji {
            get {
                return ResourceManager.GetString("MaterijalPodTomOznakomNePostoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv projekta.
        /// </summary>
        public static string NazivProjekta {
            get {
                return ResourceManager.GetString("NazivProjekta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv zone.
        /// </summary>
        public static string NazivZone {
            get {
                return ResourceManager.GetString("NazivZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neophodno je uneti broj kartice zaposlenog..
        /// </summary>
        public static string NeophnodnoJeUnetiBrojKarticeZaposlenog {
            get {
                return ResourceManager.GetString("NeophnodnoJeUnetiBrojKarticeZaposlenog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neophodno je uneti broj..
        /// </summary>
        public static string NeophodnoJeUnetiBroj {
            get {
                return ResourceManager.GetString("NeophodnoJeUnetiBroj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neophodno je uneti količinu..
        /// </summary>
        public static string NeophodnoJeUnetiKolicinu {
            get {
                return ResourceManager.GetString("NeophodnoJeUnetiKolicinu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neophodno je uneti materijal..
        /// </summary>
        public static string NeophodnoJeUnetiMaterijal {
            get {
                return ResourceManager.GetString("NeophodnoJeUnetiMaterijal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neophodno je uneti potvrdu količine..
        /// </summary>
        public static string NeophodnoJeUnetiPotvrduKolicine {
            get {
                return ResourceManager.GetString("NeophodnoJeUnetiPotvrduKolicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjava korisnika.
        /// </summary>
        public static string OdjavaKorisnika {
            get {
                return ResourceManager.GetString("OdjavaKorisnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcije.
        /// </summary>
        public static string Opcije {
            get {
                return ResourceManager.GetString("Opcije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznaka materijala.
        /// </summary>
        public static string OznakaMaterijala {
            get {
                return ResourceManager.GetString("OznakaMaterijala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počisti polja.
        /// </summary>
        public static string PocistiPolja {
            get {
                return ResourceManager.GetString("PocistiPolja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o korisniku.
        /// </summary>
        public static string PodaciOKorisniku {
            get {
                return ResourceManager.GetString("PodaciOKorisniku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polja količina i potvrda količine moraju biti ista..
        /// </summary>
        public static string PoljaKolicinaIPotvrdaMorajuBitiIste {
            get {
                return ResourceManager.GetString("PoljaKolicinaIPotvrdaMorajuBitiIste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda količine.
        /// </summary>
        public static string PotvrdaKolicine {
            get {
                return ResourceManager.GetString("PotvrdaKolicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled skeniranih količina.
        /// </summary>
        public static string PregledSkeniranihKolicina {
            get {
                return ResourceManager.GetString("PregledSkeniranihKolicina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        public static string Prijava {
            get {
                return ResourceManager.GetString("Prijava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava na aplikaciju.
        /// </summary>
        public static string PrijavaNaAplikaciju {
            get {
                return ResourceManager.GetString("PrijavaNaAplikaciju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekat.
        /// </summary>
        public static string Projekat {
            get {
                return ResourceManager.GetString("Projekat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj unos.
        /// </summary>
        public static string SacuvajUnos {
            get {
                return ResourceManager.GetString("SacuvajUnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Zona {
            get {
                return ResourceManager.GetString("Zona", resourceCulture);
            }
        }
    }
}
